# Generated by Django 2.1.7 on 2019-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(db_column='base__id', primary_key=True, serialize=False)),
                ('problema', models.TextField(db_column='baseprbl', max_length=255)),
                ('algoritmo', models.TextField(db_column='basealgr', max_length=255, null=True, blank=True)),
                ('solucion', models.TextField(blank=True, db_column='baseslcn', null=True)),
                ('clave', models.CharField(db_column='baseclve', max_length=127, null=True, blank=True)),
                ('referencia', models.TextField(db_column='baserefe', max_length=255, null=True, blank=True)),
                ('observacion', models.TextField(db_column='baseobsr', max_length=255, null=True, blank=True)),
                ('fecha', models.DateTimeField(auto_now=True, db_column='basefcha', null=True, blank=True)),
            ],
            options={
                'db_table': 'base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(db_column='prfl__id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='prfldscr', max_length=63)),
            ],
            options={
                'db_table': 'prfl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(db_column='sesn__id', primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(db_column='sesnfcin')),
                ('fin', models.DateTimeField(db_column='sesnfcfn')),
            ],
            options={
                'db_table': 'sesn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(db_column='tema__id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='temadscr', max_length=63)),
            ],
            options={
                'db_table': 'tema',
                'managed': False,
            },
        ),
    ]
