# Generated by Django 2.2 on 2019-04-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(db_column='tema__id', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='temadscr', max_length=63)),
            ],
            options={
                'db_table': 'tema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(db_column='base__id', primary_key=True, serialize=False)),
                ('problema', models.TextField(db_column='baseprbl', max_length=255)),
                ('algoritmo', models.TextField(db_column='basealgr', max_length=255)),
                ('solucion', models.TextField(blank=True, db_column='baseslcn')),
                ('clave', models.CharField(db_column='baseclve', max_length=127)),
                ('referencia', models.TextField(db_column='baserefe', max_length=255)),
                ('observacion', models.TextField(db_column='baseobsr', max_length=255)),
                ('fecha', models.DateTimeField(auto_now=True, db_column='basefcha')),
                ('tema', models.ForeignKey(db_column='tema__id', on_delete=django.db.models.deletion.CASCADE, to='base.Tema')),
            ],
            options={
                'db_table': 'base',
                'managed': True,
            },
        ),
    ]
