# Generated by Django 2.2 on 2019-06-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(db_column='base__id', primary_key=True, serialize=False)),
                ('problema', models.TextField(db_column='baseprbl', max_length=255)),
                ('algoritmo', models.TextField(db_column='basealgr', max_length=255)),
                ('solucion', models.TextField(blank=True, db_column='baseslcn')),
                ('clave', models.CharField(blank=True, db_column='baseclve', max_length=127)),
                ('referencia', models.TextField(blank=True, db_column='baserefe', max_length=255)),
                ('observacion', models.TextField(blank=True, db_column='baseobsr', max_length=255)),
                ('fecha', models.DateTimeField(auto_now=True, db_column='basefcha')),
            ],
            options={
                'db_table': 'base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(db_column='prfl__id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='prfldscr', max_length=63)),
            ],
            options={
                'db_table': 'prfl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(db_column='sesn__id', primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(db_column='sesnfcin')),
                ('fin', models.DateTimeField(db_column='sesnfcfn')),
            ],
            options={
                'db_table': 'sesn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(db_column='tema__id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='temadscr', max_length=63)),
            ],
            options={
                'db_table': 'tema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(db_column='accn__id', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='accnonmbr', max_length=63)),
                ('url', models.TextField(db_column='accn_url', max_length=31)),
                ('orden', models.IntegerField(db_column='accnordn')),
            ],
            options={
                'db_table': 'accn',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(db_column='mdlo__id', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='mdlonmbr', max_length=255)),
                ('orden', models.IntegerField(db_column='mdloordn')),
            ],
            options={
                'db_table': 'mdlo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='accion',
            name='modulo',
            field=models.ForeignKey(db_column='mdlo__id', on_delete=django.db.models.deletion.CASCADE, to='base.Modulo'),
        ),
    ]
