# Generated by Django 2.2 on 2019-04-23 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(db_column='prfl__id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='prfldscr', max_length=63)),
            ],
            options={
                'db_table': 'prfl',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(db_column='sesn__id', primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(db_column='sesnfcin')),
                ('fin', models.DateTimeField(db_column='sesnfcfn')),
                ('usro', models.ForeignKey(db_column='usro__id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesn',
                'managed': True,
            },
        ),
    ]
